name = "remix-passwordless-durable-user"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2023-01-21"

[durable_objects]
bindings = [{ name = "DO_USER", class_name = "DurableObjectUser" }]

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectUser"]
